In [ ]:
L=[1 ,2 ,3]
print(L)
len (L)
L. append (0)
L[ -1]
L
L. insert (3,"a")
L
u=L.pop (3)
u
L
L=L +[2]*3
L
L [0]=5
L
L. count (2)
L. count (8)
L. index (2)
L. index (3)
L. index (0)
2 in L
10 in L

[1, 2, 3]


False

exo3

In [1]:
import numpy as np
print(np.__version__)


1.26.4


In [4]:
import numpy as np
def Mat(n):
    matrix = np.zeros((n,n))
    for i in range(n):
        matrix[i,0:i+1]=1/(i+1)
    return matrix

Mat(5)

array([[1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.5       , 0.5       , 0.        , 0.        , 0.        ],
       [0.33333333, 0.33333333, 0.33333333, 0.        , 0.        ],
       [0.25      , 0.25      , 0.25      , 0.25      , 0.        ],
       [0.2       , 0.2       , 0.2       , 0.2       , 0.2       ]])

In [5]:
def Mat2(n):
    matrix = np.zeros((n,n))
    for i in range(n-1):
        matrix[i,i+1]=1
        matrix[i+1,i]=1
    return matrix

Mat2(5)

array([[0., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 1.],
       [0., 0., 0., 1., 0.]])

In [6]:
def matM(x):
    n=len(x)
    matrix = np.zeros((n,2))
    for i in range(n):
        matrix[i,0]=x[i]
        matrix[i,1]=0
    return matrix
matM([1,2,3,4,5])

array([[1., 0.],
       [2., 0.],
       [3., 0.],
       [4., 0.],
       [5., 0.]])

In [ ]:
import math as m 
def un(n,u0):
    if n==0:
        return u0
    else:
        return un(