# Tp 2 - sup : Choix du pas dans la descente de gradient

### Objectifs pédagogiques du TP
Dans cette séance, nous allons étudier l’influence du choix du pas de descente dans les méthodes de gradient.
Les étudiants vont :
1. Implémenter la condition d’Armijo ;
2. Implémenter la méthode de rebroussement (Backtracking) ;
3. Comparer :
    * pas fixe ;
    * Armijo ;
    * rebroussement ;
4. Observer :
    * vitesse de convergence ;
    * stabilité ;
    * qualité de la solution.

### Table
- [1. Rappel théorique](#1)
- [2. Fonction test](#2)
    - [2.1 Descente de gradient avec pas fixe](#2.1)
    - [2.2 Condition d’Armijo](#2.2)
    - [2.3 Méthode de rebroussement](#2.3)
- [3. Descente de gradient avec rebroussement](#3)
- [4. Tableau d’analyse à compléter](#4)

<a name='1'></a>

### 1. Rappel théorique

#### Condition d’Armijo
On dit que $t\geq 0$ satisfait la condition d’Armijo si :
$$f(x+t d) \leq f(x)+\alpha t \langle \nabla f(x), d \rangle$$
avec :
* $0<\alpha<1$
* $d$ direction de descente.

#### Méthode de rebroussement
On cherche un pas :
$$\delta^\star = \beta^N$$
tel que :
$$f(x+\beta^n d) \leq f(x)+\alpha \beta^n \langle \nabla f(x), d\rangle$$

<a name='2'></a>

### 2. Fonction test
Nous allons utiliser une fonction quadratique simple.

**Fonction** : $f(x,y)=x^2+4y^2$
**Gradient** : $\nabla f(x,y)=\begin{bmatrix}2x\\8y\end{bmatrix}$

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# --------------------------------------------------
# Fonction objectif
# --------------------------------------------------

def f(x):

    return x[0]**2 + 4*x[1]**2

# --------------------------------------------------
# Gradient
# --------------------------------------------------

def grad_f(x):

    return np.array([
        2*x[0],
        8*x[1]
    ])

[[2.83348981 1.39229452 0.57838509]
 [1.74568463 1.86025263 2.05267205]
 [0.31031267 2.2364273  0.84593721]
 [2.26027376 2.37811689 1.88220179]
 [1.33046653 2.89039606 2.69119966]
 [0.59041286 1.7878534  1.72013084]
 [2.11484806 2.78778606 0.15368949]
 [0.40443597 0.35108552 1.09417428]
 [2.41023251 2.91072816 0.99893778]
 [1.43525962 0.53681234 2.70760347]]


<a name='2.1'></a>

#### 2.1 Descente de gradient avec pas fixe

**Formule** :
$x^{(k+1)} = x^{(k)} - \eta \nabla f(x^{(k)})$

In [ ]:
def gradient_descent_fixed_step(
    x0,
    learning_rate=0.1,
    max_iter=50
):

    x = x0.copy()

    history = [x.copy()]

    for k in range(max_iter):

        # ==============================
        # Question 1
        # Calculer le gradient
        # ==============================

        grad = grad_f(x)

        # ==============================
        # Question 2
        # Mise à jour
        # ==============================

        x = x - learning_rate * grad

        history.append(x.copy())

    return np.array(history)


<a name='2.2'></a>

#### 2.2 Condition d’Armijo

**Principe** :
Nous voulons vérifier si un pas $t$ diminue suffisamment la fonction.

In [ ]:
def armijo_condition(
    f,
    grad_f,
    x,
    d,
    t,
    alpha=0.1
):

    # ==================================
    # Question 3
    # Calculer le membre gauche
    # ==================================

    left = f(x + t * d)

    # ==================================
    # Question 4
    # Calculer le membre droit
    # ==================================

    right = f(x) + alpha * t * np.dot(grad_f(x), d)

    return left <= right


<a name='2.3'></a>

#### 2.3 Méthode de rebroussement

**Principe** :
On part d’un grand pas puis on réduit progressivement,
$1,\beta,\beta^2,\beta^3,\dots$
jusqu’à satisfaire l'inégalité.

In [ ]:
def backtracking_line_search(
    f,
    grad_f,
    x,
    d,
    alpha=0.1,
    beta=0.5
):

    t = 1.0

    # ==================================
    # Question 5
    # Compléter la boucle
    # ==================================

    while not armijo_condition(f, grad_f, x, d, t, alpha):

        # ==============================
        # Question 6
        # Réduire le pas
        # ==============================

        t = beta * t

    return t


<a name='3'></a>

### 3. Descente de gradient avec rebroussement

In [2]:
def gradient_descent_backtracking(
    x0,
    max_iter=50
):

    x = x0.copy()

    history = [x.copy()]

    for k in range(max_iter):

        # ==============================
        # Question 7
        # Gradient
        # ==============================

        grad = grad_f(x)

        # Direction de descente
        d = -grad

        # ==============================
        # Question 8
        # Calcul du pas
        # ==============================

        t = backtracking_line_search(f, grad_f, x, d)

        # ==============================
        # Question 9
        # Mise à jour
        # ==============================

        x = x + t * d

        history.append(x.copy())

    return np.array(history)


In [3]:
## Exécution des algorithmes
x0 = np.array([8.0,8.0])

# Pas fixe
history_fixed = gradient_descent_fixed_step(
    x0,
    learning_rate=0.1
)

# Backtracking
history_backtracking = gradient_descent_backtracking(
    x0
)

print("Dernier point (pas fixe)")
print(history_fixed[-1])

print("\nDernier point (backtracking)")
print(history_backtracking[-1])

## Visualisation
plt.figure(figsize=(8,6))

plt.plot(
    history_fixed[:,0],
    history_fixed[:,1],
    'o-',
    label='Pas fixe'
)

plt.plot(
    history_backtracking[:,0],
    history_backtracking[:,1],
    'o-',
    label='Backtracking'
)

plt.xlabel("x")
plt.ylabel("y")

plt.legend()

plt.title(
    "Comparaison des trajectoires"
)

plt.grid()

plt.show()

NameError: name 'np' is not defined

<a name='4'></a>

### 4. Tableau d’analyse à compléter
**Tableau 1 — Influence du pas fixe**

| Learning rate ($\eta$) | Nombre d’itérations | Stable ? | Rapide ? | Observation |
| -------------------- | ------------------- | -------- | -------- | ----------- |
| 0.001 | Beaucoup | Oui | Non | Convergence très lente, petits déplacements. |
| 0.01 | Moyen | Oui | Moyen | Bon comportement mais encore progressif. |
| 0.1 | Peu | Oui sur cet exemple | Oui | Bon compromis pour $f(x,y)=x^2+4y^2$. |
| 0.5 | Divergence/oscillation | Non | Non | Trop grand dans la direction $y$, oscillations fortes. |
| 1.0 | Divergence | Non | Non | Les itérations explosent. |

**Questions d’analyse**
1. Quand le pas est trop petit, la fonction diminue mais très lentement : il faut beaucoup d'itérations.
2. Quand le pas est trop grand, on dépasse le minimum, puis on oscille ou on diverge.
3. Les oscillations apparaissent parce que la courbure n'est pas la même dans toutes les directions ; ici la direction $y$ est plus raide car le coefficient est $4$.

**Tableau 2 — Comparaison des méthodes**

| Méthode | Choix du pas | Stable | Rapide | Facile à régler | Observation |
| ------- | ------------ | ------ | ------ | --------------- | ----------- |
| Gradient classique | Pas fixe | Dépend de $\eta$ | Dépend de $\eta$ | Non | Très sensible au choix du pas. |
| Armijo | Pas adaptatif | Oui | Oui | Moyen | Garantit une diminution suffisante si le pas est accepté. |
| Rebroussement | Pas adaptatif | Oui | Oui | Oui | Réduit automatiquement le pas jusqu'à satisfaire Armijo. |

**Questions théoriques**

- **Question 10**
Le rebroussement est plus robuste car il commence avec un pas candidat puis le réduit automatiquement si la diminution n'est pas suffisante. Il évite donc de choisir manuellement un pas fixe optimal.

- **Question 11**
Un grand pas peut provoquer une divergence car l'itération dépasse le minimum et arrive dans une zone où la fonction est plus grande. Si cela se répète, les points s'éloignent au lieu de se rapprocher du minimiseur.

- **Question 12**
La condition d'Armijo impose
$$f(x+td) \leq f(x)+lpha t\langle 
abla f(x),d
angle.$$
Si $d$ est une direction de descente, alors $\langle 
abla f(x),d
angle<0$, donc le membre droit est strictement inférieur à $f(x)$ pour $t>0$. La fonction diminue donc d'une quantité suffisante, proportionnelle à la pente prédite.

- **Extension possible**
Pour $f(x,y)=x^2+100y^2$, la convergence devient plus difficile car la fonction est très mal conditionnée : la courbure selon $y$ est beaucoup plus forte que selon $x$. Un pas fixe doit être très petit pour rester stable, ce qui ralentit la direction $x$. Le backtracking est généralement plus robuste car il adapte le pas à la diminution réelle.
